--liquibase formatted sql

--changeset VolodymyrBoiechko:001-create-manufacturer
CREATE TABLE manufacturer
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL
);
