--liquibase formatted sql

--changeset VolodymyrBoiechko:002-create-beer
CREATE TABLE beer
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)  NOT NULL,
    abv             NUMERIC(4, 2) NOT NULL,
    type            VARCHAR(50)   NOT NULL,
    description     TEXT,
    manufacturer_id BIGINT        NOT NULL,

    CONSTRAINT fk_beer_manufacturer FOREIGN KEY (manufacturer_id) REFERENCES manufacturer (id) ON DELETE CASCADE
);

CREATE INDEX idx_beer_manufacturer_id ON beer (manufacturer_id);
