--liquibase formatted sql

--changeset VolodymyrBoiechko:003-create-app-user
CREATE TABLE app_user
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(100) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    role            VARCHAR(50)  NOT NULL,
    manufacturer_id BIGINT,

    CONSTRAINT uq_app_user_username UNIQUE (username),
    CONSTRAINT fk_app_user_manufacturer FOREIGN KEY (manufacturer_id) REFERENCES manufacturer (id) ON DELETE SET NULL
);
CREATE INDEX idx_app_user_manufacturer_id ON app_user (manufacturer_id);
