apiVersion: v1
kind: ConfigMap
metadata:
  name: beer-catalogue-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_PORT: "5432"
  DB_NAME: "beercatalogue"
  DB_HOST: "<RDS endpoint from: terraform output rds_endpoint>"
